version: "3.8"

services:
  frontend:
    container_name: player-city-fe
    image: player-city-fe:latest
    tty: true
    build:
      context: ./frontend
    ports:
      - 3002:80
    networks:
      - pol-network
  backend:
    container_name: player-city-be
    image: player-city-be:latest
    tty: true
    build:
      context: ./backend
    ports:
      - 8002:8000
    networks:
      - pol-network

  nginx:
    container_name: player-city-nginx
    image: player-city-nginx:latest
    tty: true
    restart: always
    build:
      context: ./nginx
    networks:
      - pol-network
    ports:
      - 8082:80
    depends_on:
      - backend
      - frontend

networks:
  pol-network:
    driver: bridge